# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/ui_files/memory_map_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 620)
        Dialog.setModal(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        self.gridLayout.addWidget(self.tableWidget, 4, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 5, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(32)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(30, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(31, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)


        for i in range(32):
            for j in range(5):
                item = QtWidgets.QTableWidgetItem()
                self.tableWidget_2.setItem(i, j, item)

        self.tableWidget_2.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "00000000"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "00000010"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "00000020"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "00000030"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "00000040"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "00000050"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "00000060"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "00000070"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "00000080"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "00000090"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "000000A0"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "000000B0"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "000000C0"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "000000D0"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "000000E0"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "000000F0"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "00"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "01"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "02"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "03"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "04"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "05"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "06"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "07"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "08"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "09"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("Dialog", "0A"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("Dialog", "0B"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("Dialog", "0C"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("Dialog", "0D"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("Dialog", "0E"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("Dialog", "0F"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.comboBox_2.setItemText(0, _translate("Dialog", "A0"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "A2"))
        self.label.setText(_translate("Dialog", "Display Mode"))
        self.label_2.setText(_translate("Dialog", "Page Number (Hex Value)"))
        self.comboBox.setItemText(0, _translate("Dialog", "Hex"))
        self.comboBox.setItemText(1, _translate("Dialog", "Decimal"))
        self.comboBox.setItemText(2, _translate("Dialog", "ASCII"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Hex Table"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "5"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "6"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "7"))
        item = self.tableWidget_2.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget_2.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "9"))
        item = self.tableWidget_2.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "10"))
        item = self.tableWidget_2.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget_2.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget_2.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget_2.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget_2.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget_2.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget_2.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "17"))
        item = self.tableWidget_2.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget_2.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "19"))
        item = self.tableWidget_2.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "20"))
        item = self.tableWidget_2.verticalHeaderItem(20)
        item.setText(_translate("Dialog", "21"))
        item = self.tableWidget_2.verticalHeaderItem(21)
        item.setText(_translate("Dialog", "22"))
        item = self.tableWidget_2.verticalHeaderItem(22)
        item.setText(_translate("Dialog", "23"))
        item = self.tableWidget_2.verticalHeaderItem(23)
        item.setText(_translate("Dialog", "24"))
        item = self.tableWidget_2.verticalHeaderItem(24)
        item.setText(_translate("Dialog", "25"))
        item = self.tableWidget_2.verticalHeaderItem(25)
        item.setText(_translate("Dialog", "26"))
        item = self.tableWidget_2.verticalHeaderItem(26)
        item.setText(_translate("Dialog", "27"))
        item = self.tableWidget_2.verticalHeaderItem(27)
        item.setText(_translate("Dialog", "28"))
        item = self.tableWidget_2.verticalHeaderItem(28)
        item.setText(_translate("Dialog", "29"))
        item = self.tableWidget_2.verticalHeaderItem(29)
        item.setText(_translate("Dialog", "30"))
        item = self.tableWidget_2.verticalHeaderItem(30)
        item.setText(_translate("Dialog", "31"))
        item = self.tableWidget_2.verticalHeaderItem(31)
        item.setText(_translate("Dialog", "32"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Page A0 Address"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "# of Bytes"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Description"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Value"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("Dialog", "0"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("Dialog", "Identifier"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("Dialog", "Type of transceiver (see Table 5-1 of SFF 8472)"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("Dialog", "Ext. Identifier"))
        item = self.tableWidget_2.item(1, 3)
        item.setText(_translate("Dialog", "Extended identifier of type of transceiver (See Table 5-2 of SFF 8472)"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("Dialog", "Connector"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("Dialog", "Code for connector type (see SFF 8024 SFF Module Management Reference Code Tables)"))
        item = self.tableWidget_2.item(3, 0)
        item.setText(_translate("Dialog", "3-10"))
        item = self.tableWidget_2.item(3, 1)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget_2.item(3, 2)
        item.setText(_translate("Dialog", "Transceiver"))
        item = self.tableWidget_2.item(3, 3)
        item.setText(_translate("Dialog", "Code for electronic or optical compatibility (see Table 5-3 of SFF 8472)"))
        item = self.tableWidget_2.item(4, 0)
        item.setText(_translate("Dialog", "11"))
        item = self.tableWidget_2.item(4, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(4, 2)
        item.setText(_translate("Dialog", "Encoding"))
        item = self.tableWidget_2.item(4, 3)
        item.setText(_translate("Dialog", "Code for high speed serial encoding algorithm (see SFF-8024 SFF \n"
"Module Management Reference Code Tables) "))
        item = self.tableWidget_2.item(5, 0)
        item.setText(_translate("Dialog", "12"))
        item = self.tableWidget_2.item(5, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(5, 2)
        item.setText(_translate("Dialog", "Signaling Rate, Nominal "))
        item = self.tableWidget_2.item(5, 3)
        item.setText(_translate("Dialog", "Nominal signaling rate, units of 100 MBd. \n"
"(see details for rates > 25.4 GBd) "))
        item = self.tableWidget_2.item(6, 0)
        item.setText(_translate("Dialog", "13"))
        item = self.tableWidget_2.item(6, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(6, 2)
        item.setText(_translate("Dialog", "Rate Identifier"))
        item = self.tableWidget_2.item(6, 3)
        item.setText(_translate("Dialog", "Type of rate select functionality (see Table 5-6 of SFF 8472) "))
        item = self.tableWidget_2.item(7, 0)
        item.setText(_translate("Dialog", "14"))
        item = self.tableWidget_2.item(7, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(7, 2)
        item.setText(_translate("Dialog", "Length (SMF, km) or Copper Cable Attenuation"))
        item = self.tableWidget_2.item(7, 3)
        item.setText(_translate("Dialog", "Link length supported for single-mode fiber, units of km, or copper \n"
"cable attenuation in dB at 12.9 GHz"))
        item = self.tableWidget_2.item(8, 0)
        item.setText(_translate("Dialog", "15"))
        item = self.tableWidget_2.item(8, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(8, 2)
        item.setText(_translate("Dialog", "Length (SMF) or Copper Cable Attenuation"))
        item = self.tableWidget_2.item(8, 3)
        item.setText(_translate("Dialog", "Link length supported for single-mode fiber, units of 100 m, or copper \n"
"cable attenuation in dB at 25.78 GHz"))
        item = self.tableWidget_2.item(9, 0)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget_2.item(9, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(9, 2)
        item.setText(_translate("Dialog", "Length (50 um, OM2)"))
        item = self.tableWidget_2.item(9, 3)
        item.setText(_translate("Dialog", "Link length supported for 50 um OM2 fiber, units of 10 m"))
        item = self.tableWidget_2.item(10, 0)
        item.setText(_translate("Dialog", "17"))
        item = self.tableWidget_2.item(10, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(10, 2)
        item.setText(_translate("Dialog", "Length (62.5um, OM1)"))
        item = self.tableWidget_2.item(10, 3)
        item.setText(_translate("Dialog", "Link length supported for 62.5 um OM1 fiber, units of 10 m"))
        item = self.tableWidget_2.item(11, 0)
        item.setText(_translate("Dialog", "18"))
        item = self.tableWidget_2.item(11, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(11, 2)
        item.setText(_translate("Dialog", "Length (OM4 or copper cable)"))
        item = self.tableWidget_2.item(11, 3)
        item.setText(_translate("Dialog", "Link length supported for 50um OM4 fiber, units of 10 m. \n"
"Alternatively, copper or direct attach cable, units of m"))
        item = self.tableWidget_2.item(12, 0)
        item.setText(_translate("Dialog", "19"))
        item = self.tableWidget_2.item(12, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(12, 2)
        item.setText(_translate("Dialog", "Length (OM3 or Cable length, additional"))
        item = self.tableWidget_2.item(12, 3)
        item.setText(_translate("Dialog", "Link length supported for 50 um OM3 fiber, units of 10 m. \n"
"Alternatively, copper or direct attach cable multiplier and base value"))
        item = self.tableWidget_2.item(13, 0)
        item.setText(_translate("Dialog", "20-35"))
        item = self.tableWidget_2.item(13, 1)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget_2.item(13, 2)
        item.setText(_translate("Dialog", "Vendor name"))
        item = self.tableWidget_2.item(13, 3)
        item.setText(_translate("Dialog", "SFP vendor name (ASCII)"))
        item = self.tableWidget_2.item(14, 0)
        item.setText(_translate("Dialog", "36"))
        item = self.tableWidget_2.item(14, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(14, 2)
        item.setText(_translate("Dialog", "Transceiver"))
        item = self.tableWidget_2.item(14, 3)
        item.setText(_translate("Dialog", "Code for electronic or optical compatibility (see Table 5-3 of SFF-8472)"))
        item = self.tableWidget_2.item(15, 0)
        item.setText(_translate("Dialog", "37-39"))
        item = self.tableWidget_2.item(15, 1)
        item.setText(_translate("Dialog", "3"))
        item = self.tableWidget_2.item(15, 2)
        item.setText(_translate("Dialog", "Vendor OUI"))
        item = self.tableWidget_2.item(15, 3)
        item.setText(_translate("Dialog", "SFP vendor IEEE company ID"))
        item = self.tableWidget_2.item(16, 0)
        item.setText(_translate("Dialog", "40-55"))
        item = self.tableWidget_2.item(16, 1)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget_2.item(16, 2)
        item.setText(_translate("Dialog", "Vendor PN"))
        item = self.tableWidget_2.item(16, 3)
        item.setText(_translate("Dialog", "Part number provided by SFP vendor (ASCII)"))
        item = self.tableWidget_2.item(17, 0)
        item.setText(_translate("Dialog", "56-59"))
        item = self.tableWidget_2.item(17, 1)
        item.setText(_translate("Dialog", "4"))
        item = self.tableWidget_2.item(17, 2)
        item.setText(_translate("Dialog", "Vendor rev"))
        item = self.tableWidget_2.item(17, 3)
        item.setText(_translate("Dialog", "Revision level for part number provided by vendor (ASCII)"))
        item = self.tableWidget_2.item(18, 0)
        item.setText(_translate("Dialog", "60-61"))
        item = self.tableWidget_2.item(18, 1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_2.item(18, 2)
        item.setText(_translate("Dialog", "Wavelength"))
        item = self.tableWidget_2.item(18, 3)
        item.setText(_translate("Dialog", "Laser wavelength (Passive/Active Cable Specification Compliance)"))
        item = self.tableWidget_2.item(19, 0)
        item.setText(_translate("Dialog", "62"))
        item = self.tableWidget_2.item(19, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(19, 2)
        item.setText(_translate("Dialog", "Fibre Channel Speed 2"))
        item = self.tableWidget_2.item(19, 3)
        item.setText(_translate("Dialog", "Transceiver\'s Fibre Channel speed capabilities"))
        item = self.tableWidget_2.item(20, 0)
        item.setText(_translate("Dialog", "63"))
        item = self.tableWidget_2.item(20, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(20, 2)
        item.setText(_translate("Dialog", "CC_BASE"))
        item = self.tableWidget_2.item(20, 3)
        item.setText(_translate("Dialog", "Check code for Base ID fields (addresses 0 to 62)"))
        item = self.tableWidget_2.item(21, 0)
        item.setText(_translate("Dialog", "64-65"))
        item = self.tableWidget_2.item(21, 1)
        item.setText(_translate("Dialog", "2"))
        item = self.tableWidget_2.item(21, 2)
        item.setText(_translate("Dialog", "Options"))
        item = self.tableWidget_2.item(21, 3)
        item.setText(_translate("Dialog", "Indicates which optional transceiver signals are implemented (see Table 8-3 of SFF-8472)"))
        item = self.tableWidget_2.item(22, 0)
        item.setText(_translate("Dialog", "66"))
        item = self.tableWidget_2.item(22, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(22, 2)
        item.setText(_translate("Dialog", "Signaling Rate, max"))
        item = self.tableWidget_2.item(22, 3)
        item.setText(_translate("Dialog", "Upper signaling rate margin, units of % (see details for rates > 25.4 GBd)"))
        item = self.tableWidget_2.item(23, 0)
        item.setText(_translate("Dialog", "67"))
        item = self.tableWidget_2.item(23, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(23, 2)
        item.setText(_translate("Dialog", "Signaling Rate, min"))
        item = self.tableWidget_2.item(23, 3)
        item.setText(_translate("Dialog", "Lower signaling rate margin, units of % (see details for rates > 25.4 GBd)"))
        item = self.tableWidget_2.item(24, 0)
        item.setText(_translate("Dialog", "68-83"))
        item = self.tableWidget_2.item(24, 1)
        item.setText(_translate("Dialog", "16"))
        item = self.tableWidget_2.item(24, 2)
        item.setText(_translate("Dialog", "Vendor SN"))
        item = self.tableWidget_2.item(24, 3)
        item.setText(_translate("Dialog", "Serial number provided by vendor (ASCII)"))
        item = self.tableWidget_2.item(25, 0)
        item.setText(_translate("Dialog", "84-91"))
        item = self.tableWidget_2.item(25, 1)
        item.setText(_translate("Dialog", "8"))
        item = self.tableWidget_2.item(25, 2)
        item.setText(_translate("Dialog", "Date code"))
        item = self.tableWidget_2.item(25, 3)
        item.setText(_translate("Dialog", "Vendor\'s manufacturing date code (see Table 8-4 of SFF-8472)"))
        item = self.tableWidget_2.item(26, 0)
        item.setText(_translate("Dialog", "92"))
        item = self.tableWidget_2.item(26, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(26, 2)
        item.setText(_translate("Dialog", "Diagnostic Monitoring Type"))
        item = self.tableWidget_2.item(26, 3)
        item.setText(_translate("Dialog", "Indicates which type of diagnostic monitoring is implemented (if any) in the transceiver (see Table 8-6 of SFF-8472)"))
        item = self.tableWidget_2.item(27, 0)
        item.setText(_translate("Dialog", "93"))
        item = self.tableWidget_2.item(27, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(27, 2)
        item.setText(_translate("Dialog", "Enhanced Options"))
        item = self.tableWidget_2.item(27, 3)
        item.setText(_translate("Dialog", "Indicates which optional enhanced features are implemented \n"
"(if any) in the transceiver (see Table 8-6 of SFF-8472)"))
        item = self.tableWidget_2.item(28, 0)
        item.setText(_translate("Dialog", "94"))
        item = self.tableWidget_2.item(28, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(28, 2)
        item.setText(_translate("Dialog", "SFF-8472 Compliance"))
        item = self.tableWidget_2.item(28, 3)
        item.setText(_translate("Dialog", "Indicates which revision of SFF-8472 the transceiver complies with. \n"
"(see Table 8-8 of SFF-8472)"))
        item = self.tableWidget_2.item(29, 0)
        item.setText(_translate("Dialog", "95"))
        item = self.tableWidget_2.item(29, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.tableWidget_2.item(29, 2)
        item.setText(_translate("Dialog", "CC_EXT"))
        item = self.tableWidget_2.item(29, 3)
        item.setText(_translate("Dialog", "Check code for the Extended ID Fields (addresses 64 to 94)"))
        item = self.tableWidget_2.item(30, 0)
        item.setText(_translate("Dialog", "96-127"))
        item = self.tableWidget_2.item(30, 1)
        item.setText(_translate("Dialog", "32"))
        item = self.tableWidget_2.item(30, 2)
        item.setText(_translate("Dialog", "Vendor Specific"))
        item = self.tableWidget_2.item(30, 3)
        item.setText(_translate("Dialog", "Vendor Specific EEPROM"))
        item = self.tableWidget_2.item(31, 0)
        item.setText(_translate("Dialog", "128-255"))
        item = self.tableWidget_2.item(31, 1)
        item.setText(_translate("Dialog", "128"))
        item = self.tableWidget_2.item(31, 2)
        item.setText(_translate("Dialog", "Reserved"))
        item = self.tableWidget_2.item(31, 3)
        item.setText(_translate("Dialog", "Reserved (was assigned to SFF-8079)"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Characteristics"))
